language: go
sudo: false
go: 
 - 1.7

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi


script:
 - go test $(go list ./... | grep -v /vendor/)
 - $GOPATH/bin/overalls -project=github.com/danielfireman/contratospublicos -covermode=count -ignore=.git,vendor -debug

after_success:
 - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service github.com/danielfireman/contratospublicos -repotoken $COVERALLS_TOKEN
